options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','--platform=linux/amd64','-t','gcr.io/$PROJECT_ID/dys-api-stock:$SHORT_SHA','.']

  - id: 'Push image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/dys-api-stock:$SHORT_SHA']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy dys-api-stock \
          --image gcr.io/$PROJECT_ID/dys-api-stock:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --service-account=sa-dys-api-stock@${PROJECT_ID}.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --port=8080 \
          --timeout=300s

images:
  - 'gcr.io/$PROJECT_ID/dys-api-stock:$SHORT_SHA'
